name: hello world
on: 
  push:
    branchs: [master]
jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "TODAY=$(date +%y-%m-%d)" >> GITHUB_ENV
      - run: echo hello world, today is $TODAY